"""fix bugs

Revision ID: e287bc0501f9
Revises: 7c318477e955
Create Date: 2026-09-18 10:15:00.230139+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e287bc0501f9'
down_revision: Union[str, Sequence[str], None] = '7c318477e955'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('check_game_or_util'), 'record', type_='check')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_check_constraint(op.f('check_game_or_util'), 'record', 'game_id IS NOT NULL AND util_id IS NULL OR game_id IS NULL AND util_id IS NOT NULL')
    # ### end Alembic commands ###
