"""rebuild db with sqlalchemy and alembic

Revision ID: 4a81bc9114fa
Revises: 
Create Date: 2026-08-21 12:32:51.442089+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a81bc9114fa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bulk_order',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('arrived_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('seller', sa.String(length=100), nullable=True),
    sa.Column('order_status', sa.String(length=100), nullable=True),
    sa.Column('total_count', sa.Integer(), nullable=True),
    sa.Column('total_cost', sa.Integer(), nullable=True),
    sa.Column('delivery_cost', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_bulk_order_order_status'), 'bulk_order', ['order_status'], unique=False)
    op.create_table('games_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_games_list_name'), 'games_list', ['name'], unique=True)
    op.create_table('utils_list',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('title')
    )
    op.create_table('record',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('purchase_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sold_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.Column('util_id', sa.Integer(), nullable=True),
    sa.Column('bulk_order_id', sa.Integer(), nullable=True),
    sa.Column('price_purchase', sa.Integer(), nullable=True),
    sa.Column('price_selling', sa.Integer(), nullable=True),
    sa.Column('price_sold', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('swap', sa.String(length=20), nullable=True),
    sa.Column('reserve', sa.Text(), nullable=True),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.CheckConstraint('(game_id IS NOT NULL AND util_id IS NULL) OR (game_id IS NULL AND util_id IS NOT NULL)', name='check_game_or_util'),
    sa.ForeignKeyConstraint(['bulk_order_id'], ['bulk_order.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['game_id'], ['games_list.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['util_id'], ['utils_list.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_record_bulk_order_id'), 'record', ['bulk_order_id'], unique=False)
    op.create_index(op.f('ix_record_game_id'), 'record', ['game_id'], unique=False)
    op.create_index(op.f('ix_record_status'), 'record', ['status'], unique=False)
    op.create_index(op.f('ix_record_util_id'), 'record', ['util_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_record_util_id'), table_name='record')
    op.drop_index(op.f('ix_record_status'), table_name='record')
    op.drop_index(op.f('ix_record_game_id'), table_name='record')
    op.drop_index(op.f('ix_record_bulk_order_id'), table_name='record')
    op.drop_table('record')
    op.drop_table('utils_list')
    op.drop_index(op.f('ix_games_list_name'), table_name='games_list')
    op.drop_table('games_list')
    op.drop_index(op.f('ix_bulk_order_order_status'), table_name='bulk_order')
    op.drop_table('bulk_order')
    # ### end Alembic commands ###
