"""rename trns to util

Revision ID: 9711b26c99b9
Revises: 3cacc047e3f6
Create Date: 2026-09-28 06:48:19.781826+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9711b26c99b9'
down_revision: Union[str, Sequence[str], None] = '3cacc047e3f6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('util_id', sa.Integer(), nullable=True))
    op.drop_index(op.f('ix_record_util_id'), table_name='record')
    op.create_index(op.f('ix_record_util_id'), 'record', ['util_id'], unique=False)
    op.drop_constraint(op.f('record_util_id_fkey'), 'record', type_='foreignkey')
    op.create_foreign_key(None, 'record', 'utils_list', ['util_id'], ['id'], ondelete='SET NULL')
    op.drop_column('record', 'util_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('record', sa.Column('util_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'record', type_='foreignkey')
    op.create_foreign_key(op.f('record_util_id_fkey'), 'record', 'utils_list', ['util_id'], ['id'], ondelete='SET NULL')
    op.drop_index(op.f('ix_record_util_id'), table_name='record')
    op.create_index(op.f('ix_record_util_id'), 'record', ['util_id'], unique=False)
    op.drop_column('record', 'util_id')
    # ### end Alembic commands ###
