"""add message_to_delete model

Revision ID: 3d2dfc9c4fae
Revises: e287bc0501f9
Create Date: 2026-09-19 09:38:25.235015+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3d2dfc9c4fae'
down_revision: Union[str, Sequence[str], None] = 'e287bc0501f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('message_to_delete',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_message_to_delete_chat_id'), 'message_to_delete', ['chat_id'], unique=False)
    op.create_index(op.f('ix_message_to_delete_user_id'), 'message_to_delete', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_message_to_delete_user_id'), table_name='message_to_delete')
    op.drop_index(op.f('ix_message_to_delete_chat_id'), table_name='message_to_delete')
    op.drop_table('message_to_delete')
    # ### end Alembic commands ###
